export enum Path {
    Root = '/',
    Auth = '/auth',
    Check = '/check',
    Login = '/login',
    Signup = '/signup',
    Users = '/users',
    GithubLogin ='/github',
    Collection = '/collection',
    Id='/:id',
    User = '/user',
    Popular = '/popular',
    Tags ='/tags',
    Tag = '/:tag',
    Topics ='/topics',
    Items ='/items',
    Likes ='/likes',
    Comments ="/comments",
    Search ="/search",
};
